package com.kdz.jarvis.network.models

data class ComicDetails(
    val characters: Characters,
    val collectedIssues: List<IssueSummary>,
    val collections: List<CollectionSummary>,
    val creators: Creators,
    val dates: List<Date>,
    val description: String,
    val diamondCode: String,
    val digitalId: String,
    val ean: String,
    val events: Events,
    val format: String,
    val id: String,
    val images: List<Thumbnail>,
    val isbn: String,
    val issn: String,
    val issueNumber: String,
    val modified: String,
    val pageCount: String,
    val prices: List<Price>,
    val resourceURI: String,
    val series: SeriesSummary,
    val stories: StoriesSummary,
    val textObjects: List<TextObject>,
    val thumbnail: Thumbnail,
    val title: String,
    val upc: String,
    val urls: List<Url>,
    val variantDescription: String,
    val variants: List<Variant>
)